version: '3.0'
services:
  web:
    build: docker
    ports:
      - "8080:80"
    links:
      - db
      - elastic
    volumes:
      - ./:/var/www/html/app/code/Alma/MonthlyPayments/
      - ./docker/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini
#      -  ../alma-monthlypayments-magento2:/var/www/html/vendor/alma/alma-monthlypayments-magento2
#      - alma-vendors:/var/www/html/vendor/alma/alma-monthlypayments-magento2/vendor
    env_file:
      - docker/env
  elastic:
    image: library/elasticsearch:7.6.2
    command: elasticsearch
    environment:
      - cluster.name=magento-es
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/http?:\/\/(localhost|local.magento)(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-logs:/usr/share/elasticsearch/logs
    healthcheck:
      test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: mysql:5.7
    user: "1000:50"
    #volumes:
    #  - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - docker/env
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8580:80"
#    links:
#      - db
volumes:
#  magento-data:
  mysql-data:
#  alma-vendors:
  es-data:
  es-logs:
